const MODAL_PRODUCT_REQUEST = "@modal/MODAL_PRODUCT_REQUEST";
const MODAL_PRODUCT_RESET = "@modal/MODAL_PRODUCT_RESET";

const MODAL_PRODUCT_ADD_SUCCESS = "@modal/MODAL_PRODUCT_ADD_SUCCESS";
const MODAL_PRODUCT_ADD_FAILED = "@modal/MODAL_PRODUCT_ADD_FAILED";

const MODAL_PRODUCT_EDIT_SUCCESS = "@modal/MODAL_PRODUCT_EDIT_SUCCESS";
const MODAL_PRODUCT_EDIT_FAILED = "@modal/MODAL_PRODUCT_EDIT_FAILED";

export { MODAL_PRODUCT_REQUEST, MODAL_PRODUCT_ADD_SUCCESS, MODAL_PRODUCT_ADD_FAILED, MODAL_PRODUCT_EDIT_SUCCESS, MODAL_PRODUCT_EDIT_FAILED, MODAL_PRODUCT_RESET };