const USER_INFO_REQUEST = '@userInfo/USER_INFO_REQUEST';
const USER_INFO_SUCCESS = '@userInfo/USER_INFO_SUCCESS';
const USER_INFO_FAILED = '@userInfo/USER_INFO_FAILED';

const USER_INFO_EDIT_SUCCESS = "@userInfo/USER_INFO_EDIT_SUCCESS";
const USER_INFO_EDIT_FAILED = "@userInfo/USER_INFO_EDIT_FAILED";

export { USER_INFO_REQUEST, USER_INFO_SUCCESS, USER_INFO_FAILED, USER_INFO_EDIT_SUCCESS, USER_INFO_EDIT_FAILED }