const USERS_MANAGEMENT_REQUEST = '@usersManagement/USERS_MANAGEMENT_REQUEST';
const USERS_MANAGEMENT_SUCCESS = '@usersManagement/USERS_MANAGEMENT_SUCCESS';
const USERS_MANAGEMENT_FAILED = '@usersManagement/USERS_MANAGEMENT_FAILED';

const USER_DELETE_REQUEST = '@usersManagement/USER_DELETE_REQUEST';
const USER_DELETE_SUCCESS = '@usersManagement/USER_DELETE_SUCCESS';
const USER_DELETE_FAILED = '@usersManagement/USER_DELETE_FAILED';

const USER_EDIT_REQUEST = '@usersManagement/USER_EDIT_REQUEST';
const USER_EDIT_SUCCESS = '@usersManagement/USER_EDIT_SUCCESS';
const USER_EDIT_FAILED = '@usersManagement/USER_EDIT_FAILED';

export { USERS_MANAGEMENT_REQUEST, USERS_MANAGEMENT_SUCCESS, USERS_MANAGEMENT_FAILED, USER_DELETE_REQUEST, USER_DELETE_SUCCESS, USER_DELETE_FAILED, USER_EDIT_REQUEST, USER_EDIT_SUCCESS, USER_EDIT_FAILED }