const PRODUCT_DETAIL_REQUEST = '@productDetail/PRODUCT_DETAIL_REQUEST';
const PRODUCT_DETAIL_SUCCESS = '@productDetail/PRODUCT_DETAIL_SUCCESS';
const PRODUCT_DETAIL_FAILED = '@productDetail/PRODUCT_DETAIL_FAILED';

const CART_MANAGEMENT_REQUEST = '@productsManagement/CART_MANAGEMENT_REQUEST';
const CART_MANAGEMENT_SUCCESS = '@productsManagement/CART_MANAGEMENT_SUCCESS';
const CART_MANAGEMENT_FAILED = '@productsManagement/CART_MANAGEMENT_FAILED';

export { PRODUCT_DETAIL_REQUEST, PRODUCT_DETAIL_SUCCESS, PRODUCT_DETAIL_FAILED, CART_MANAGEMENT_REQUEST, CART_MANAGEMENT_SUCCESS, CART_MANAGEMENT_FAILED }