const MODAL_REQUEST = "@modal/MODAL_REQUEST";
const MODAL_RESET = "@modal/MODAL_RESET";

const MODAL_ADD_SUCCESS = "@modal/MODAL_ADD_SUCCESS";
const MODAL_ADD_FAILED = "@modal/MODAL_ADD_FAILED";

const MODAL_EDIT_SUCCESS = "@modal/MODAL_EDIT_SUCCESS";
const MODAL_EDIT_FAILED = "@modal/MODAL_EDIT_FAILED";

export { MODAL_REQUEST, MODAL_ADD_SUCCESS, MODAL_ADD_FAILED, MODAL_EDIT_SUCCESS, MODAL_EDIT_FAILED, MODAL_RESET };