const MODAL_SELLER_REQUEST = "@modal/MODAL_SELLER_REQUEST";
const MODAL_SELLER_RESET = "@modal/MODAL_SELLER_RESET";

const MODAL_SELLER_ADD_SUCCESS = "@modal/MODAL_SELLER_ADD_SUCCESS";
const MODAL_SELLER_ADD_FAILED = "@modal/MODAL_SELLER_ADD_FAILED";

const MODAL_SELLER_EDIT_SUCCESS = "@modal/MODAL_SELLER_EDIT_SUCCESS";
const MODAL_SELLER_EDIT_FAILED = "@modal/MODAL_SELLER_EDIT_FAILED";

const USERS_MANAGEMENT_REQUEST = '@sellersManagement/USERS_MANAGEMENT_REQUEST';
const USERS_MANAGEMENT_SUCCESS = '@sellersManagement/USERS_MANAGEMENT_SUCCESS';
const USERS_MANAGEMENT_FAILED = '@sellersManagement/USERS_MANAGEMENT_FAILED';

export { MODAL_SELLER_REQUEST, MODAL_SELLER_ADD_SUCCESS, MODAL_SELLER_ADD_FAILED, MODAL_SELLER_EDIT_SUCCESS, MODAL_SELLER_EDIT_FAILED, MODAL_SELLER_RESET,USERS_MANAGEMENT_REQUEST, USERS_MANAGEMENT_SUCCESS, USERS_MANAGEMENT_FAILED  };