const PAY_MANAGEMENT_REQUEST = '@payment/PAY_MANAGEMENT_REQUEST';
const PAY_MANAGEMENT_SUCCESS = '@payment/PAY_MANAGEMENT_SUCCESS';
const PAY_MANAGEMENT_FAILED = 'payment/PAY_MANAGEMENT_FAILED';

const BALANCE_MANAGEMENT_REQUEST = '@balanceManagement/BALANCE_MANAGEMENT_REQUEST';
const BALANCE_MANAGEMENT_SUCCESS = '@balanceManagement/BALANCE_MANAGEMENT_SUCCESS';
const BALANCE_MANAGEMENT_FAILED = '@balanceManagement/BALANCE_MANAGEMENT_FAILED';

export { PAY_MANAGEMENT_REQUEST, PAY_MANAGEMENT_SUCCESS, PAY_MANAGEMENT_FAILED, BALANCE_MANAGEMENT_REQUEST, BALANCE_MANAGEMENT_SUCCESS, BALANCE_MANAGEMENT_FAILED }