const SELLERS_MANAGEMENT_REQUEST = '@sellerManagement/SELLERS_MANAGEMENT_REQUEST';
const SELLERS_MANAGEMENT_SUCCESS = '@sellersManagement/SELLERS_MANAGEMENT_SUCCESS';
const SELLERS_MANAGEMENT_FAILED = '@sellersManagement/SELLERS_MANAGEMENT_FAILED';

const USERS_MANAGEMENT_REQUEST = '@sellersManagement/USERS_MANAGEMENT_REQUEST';
const USERS_MANAGEMENT_SUCCESS = '@sellersManagement/USERS_MANAGEMENT_SUCCESS';
const USERS_MANAGEMENT_FAILED = '@sellersManagement/USERS_MANAGEMENT_FAILED';

export { USERS_MANAGEMENT_REQUEST, USERS_MANAGEMENT_SUCCESS, USERS_MANAGEMENT_FAILED,SELLERS_MANAGEMENT_REQUEST, SELLERS_MANAGEMENT_SUCCESS, SELLERS_MANAGEMENT_FAILED}