const LOGIN_REQUEST = '@login/LOGIN_REQUEST';
const LOGIN_SUCCESS = '@login/LOGIN_SUCCESS';
const LOGIN_FAILED = '@login/LOGIN_FAILED';
const LOGIN_RESET = '@login/LOGIN_RESET';

export { LOGIN_REQUEST, LOGIN_SUCCESS, LOGIN_FAILED, LOGIN_RESET }