const ORDERS_MANAGEMENT_REQUEST = '@ordersManagement/ORDERS_MANAGEMENT_REQUEST';
const ORDERS_MANAGEMENT_SUCCESS = '@ordersManagement/ORDERS_MANAGEMENT_SUCCESS';
const ORDERS_MANAGEMENT_FAILED = '@ordersManagement/ORDERS_MANAGEMENT_FAILED';

const ORDERS_BYID_MANAGEMENT_REQUEST = '@ordersManagement/ORDERS_MANAGEMENT_REQUEST';
const ORDERS_BYID_MANAGEMENT_SUCCESS = '@ordersManagement/ORDERS_MANAGEMENT_SUCCESS';
const ORDERS_BYID_MANAGEMENT_FAILED = '@ordersManagement/ORDERS_MANAGEMENT_FAILED';

const UPDATE_STATUS_MANAGEMENT_REQUEST = '@ordersManagement/UPDATE_STATUS_MANAGEMENT_REQUEST';
const UPDATE_STATUS_MANAGEMENT_SUCCESS = '@ordersManagement/UPDATE_STATUS_MANAGEMENT_SUCCESS';
const UPDATE_STATUS_MANAGEMENT_FAILED = '@ordersManagement/UPDATE_STATUS_MANAGEMENT_FAILED';

export { ORDERS_MANAGEMENT_REQUEST, ORDERS_MANAGEMENT_SUCCESS, ORDERS_MANAGEMENT_FAILED, ORDERS_BYID_MANAGEMENT_REQUEST, ORDERS_BYID_MANAGEMENT_SUCCESS, ORDERS_BYID_MANAGEMENT_FAILED, UPDATE_STATUS_MANAGEMENT_REQUEST, UPDATE_STATUS_MANAGEMENT_SUCCESS, UPDATE_STATUS_MANAGEMENT_FAILED }