const SIGN_UP_REQUEST = "@signUp/SIGN_UP_REQUEST";
const SIGN_UP_SUCCESS = "@signUp/SIGN_UP_SUCCESS";
const SIGN_UP_FAILED = "@signUp/SIGN_UP_FAILED";
const SIGN_UP_RESET = "@signUp/SIGN_UP_RESET";

export { SIGN_UP_REQUEST, SIGN_UP_SUCCESS, SIGN_UP_FAILED, SIGN_UP_RESET };