const PRODUCTS_MANAGEMENT_REQUEST = '@productsManagement/PRODUCTS_MANAGEMENT_REQUEST';
const PRODUCTS_MANAGEMENT_SUCCESS = '@productsManagement/PRODUCTS_MANAGEMENT_SUCCESS';
const PRODUCTS_MANAGEMENT_FAILED = '@productsManagement/PRODUCTS_MANAGEMENT_FAILED';

const PRODUCTS_DELETE_REQUEST = '@productsManagement/PRODUCTS_DELETE_REQUEST';
const PRODUCTS_DELETE_SUCCESS = '@productsManagement/PRODUCTS_DELETE_SUCCESS';
const PRODUCTS_DELETE_FAILED = '@productsManagement/PRODUCTS_DELETE_FAILED';

const PRODUCTS_EDIT_REQUEST = '@productsManagement/PRODUCTS_EDIT_REQUEST';
const PRODUCTS_EDIT_SUCCESS = '@productrsManagement/PRODUCTS_EDIT_SUCCESS';
const PRODUCTS_EDIT_FAILED = '@productsManagement/PRODUCTS_EDIT_FAILED';

export { PRODUCTS_MANAGEMENT_REQUEST, PRODUCTS_MANAGEMENT_SUCCESS, PRODUCTS_MANAGEMENT_FAILED, PRODUCTS_DELETE_REQUEST, PRODUCTS_DELETE_SUCCESS, PRODUCTS_DELETE_FAILED, PRODUCTS_EDIT_REQUEST, PRODUCTS_EDIT_SUCCESS, PRODUCTS_EDIT_FAILED }