const CART_MANAGEMENT_REQUEST = '@cartsManagement/CART_MANAGEMENT_REQUEST';
const CART_MANAGEMENT_SUCCESS = '@cartsManagement/CART_MANAGEMENT_SUCCESS';
const CART_MANAGEMENT_FAILED = '@cartsManagement/CART_MANAGEMENT_FAILED';

const PRODUCTS_MANAGEMENT_REQUEST = '@cartsManagement/PRODUCTS_MANAGEMENT_REQUEST';
const PRODUCTS_MANAGEMENT_SUCCESS = '@cartsManagement/PRODUCTS_MANAGEMENT_SUCCESS';
const PRODUCTS_MANAGEMENT_FAILED = '@cartsManagement/PRODUCTS_MANAGEMENT_FAILED';

const PRODUCTS_DELETE_REQUEST = '@cartsManagement/PRODUCTS_DELETE_REQUEST';
const PRODUCTS_DELETE_SUCCESS = '@cartsManagement/PRODUCTS_DELETE_SUCCESS';
const PRODUCTS_DELETE_FAILED = '@cartsManagement/PRODUCTS_DELETE_FAILED';

export { CART_MANAGEMENT_REQUEST, CART_MANAGEMENT_SUCCESS, CART_MANAGEMENT_FAILED, PRODUCTS_MANAGEMENT_REQUEST, PRODUCTS_MANAGEMENT_SUCCESS, PRODUCTS_MANAGEMENT_FAILED, PRODUCTS_DELETE_REQUEST, PRODUCTS_DELETE_SUCCESS, PRODUCTS_DELETE_FAILED}